students/config/routes.rb
Students::Application.routes.draw do
  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

end

students/app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :date_of_birth, :family_name, :given_name, :grade_point_average, :middle_name, :start_date
  has_many :awards, :dependent => :destroy
  has_and_belongs_to_many :courses

  def name
    given_name + " " + family_name
  end

  def enrolled_in?(course)
    self.courses.include?(course)
  end

  def unenrolled_courses
    Course.find(:all) - self.courses
  end
end

students/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # POST /students/1/course_add?course_id=2
  def course_add
    #Convert ids from routing to objects
    @student = Student.find(params[:id])
    @course = Course.find(params[:course])
    if not @student.enrolled_in?(@course)
      #add course to list using << operator
      @student.courses << @course
      flash[:notice] = 'Student was successfully enrolled'
    else
      flash[:error] = 'Student was already enrolled'
    end
    redirect_to :action => :courses, :id => @student
  end

  #POST /students/1/course_remove?courses[]=
  def course_remove
    # Convert ids from routing to object
    @student = Student.find(params[:id])
    # get list of courses to remove from query strying
    course_ids = params[:courses]
    unless course_ids.blank?
      course_ids.each do |course_id|
        course = Course.find(course_id)
          if @student.enrolled_in?(course)
            logger.info "Removing student from course #{course.id}"
            student.courses.delete(course)
            flash[:notice] = 'Course was successfully deleted'
          end
      end
    end
    redirect_to :action => :courses, :id => @student
  end

  def courses
    @student = Student.find(params[:id])
    @courses = @student.courses
  end

  # GET /students
  # GET /students.json
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

students/app/helpers/students_helper.rb
module StudentsHelper
end

students/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %><br />
    <%= f.text_field :given_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :family_name %><br />
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :grade_point_average %><br />
    <%= f.text_field :grade_point_average %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

students/app/views/students/courses.html.erb
<h1><%= @student.name %>'s courses</h1>

<% if @courses.length > 0 %>
  <%= form_tag(course_remove_student_path(@student)) do %>
<!--  
  TODO: How is course_remove_student_path determined, when 
  course_remove is a method under the student controller??
--!>
  <table>
    <tr>
      <th>Course</th>
      <th>Remove?</th>
    </tr>
  <% for course in @courses do %>
    <tr>
      <td><%= course.name %></td>
      <td><%= check_box_tag "courses[]", course.id %></td>
    </tr>
  <% end %>
  </table>
  <br />

  <%= submit_tag 'Remove checked courses' %>
  <% end %>

<% else %>
  <p>Not enrolled in any courses yet.</p>
<% end %>

<h2>Enroll in new course</h2>

<% if @student.courses.count < Course.count then %>
  <%= form_tag(course_add_student_path(@student)) do %>
    <%= select_tag(:course,
      options_from_collection_for_select(@student.unenrolled_courses,
        :id, :name)) %>
    <%= submit_tag 'Enroll' %>
  <% end %>
<% else %>
  <p><%= @student.name %> is enrolled in every course.</p>
<% end %>

<p><%= link_to "Back", @student %></p>

students/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

students/app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <tr>
    <th>Given name</th>
    <th>Middle name</th>
    <th>Family name</th>
    <th>Date of birth</th>
    <th>Grade point average</th>
    <th>Start date</th>
    <th>Courses</th>
    <th>Awards</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.given_name %></td>
    <td><%= student.middle_name %></td>
    <td><%= student.family_name %></td>
    <td><%= student.date_of_birth %></td>
    <td><%= student.grade_point_average %></td>
    <td><%= student.start_date %></td>
    <td><%= student.courses.count %></td>
    <td><%= student.awards.count %></td>
    <td><%= link_to 'Show', student %></td>
    <td><%= link_to 'Edit', edit_student_path(student) %></td>
    <td><%= link_to 'Courses', courses_student_path(student) %></td>
    <td><%= link_to 'Awards', student_awards_path(student) %></td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Student', new_student_path %>

students/app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

students/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Given name:</b>
  <%= @student.given_name %>
</p>

<p>
  <b>Middle name:</b>
  <%= @student.middle_name %>
</p>

<p>
  <b>Family name:</b>
  <%= @student.family_name %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @student.date_of_birth %>
</p>

<p>
  <b>Grade point average:</b>
  <%= @student.grade_point_average %>
</p>

<p>
  <b>Start date:</b>
  <%= @student.start_date %>
</p>

<!--
<% if @student.awards.count > 0 %>
<h3>Awards</h3>
<table>
  <tr>
    <th>Name</th>
    <th>Year</th>
    <th>Student</th>
  </tr>
<% for award in @student.awards %>
  <tr>
    <td><%= award.name %></td>
    <td><%= award.year %></td>
    <td><%= award.student.name %></td>
  </tr>
<% end %>

</table>
<% end %>
-->

<p>
  <b>Courses: </b>
  <% if !@student.courses.empty? %>
    <%= @student.courses.collect {|c| link_to(c.name, c)}.join(", ").html_safe %>
  <% else %>
    Not enrolled in any courses yet.
  <% end %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Courses', courses_student_path(@student) %> |
<%= link_to 'Awards', student_awards_path(@student) %> |
<%= link_to 'Back', students_path %>