students/config/routes.rb
Students::Application.routes.draw do
  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

end

students/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  def roll
    @course = Course.find(params[:id])
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :no_content }
    end
  end
end

students/app/helpers/courses_helper.rb
module CoursesHelper
end

students/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

students/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

students/app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Enrolled</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
    <td><%= course.students.count %></td>
    <td><%= course.name %></td>
    <td><%= link_to 'Show', course %></td>
    <td><%= link_to 'Edit', edit_course_path(course) %></td>
    <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Course', new_course_path %>

students/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

students/app/views/courses/roll.html.erb
<h1>Roll for <%= @course.name %> </h1>

<% if @course.students.length > 0 %>
  <table>
    <tr>
      <th>Student</th>
      <th>GPA</th>
    </tr>

  <% @course.students each do |student| %>
    <tr>
      <td><%= link_to student.name, student %></td>
      <td><%= student.grade_point_average %></td>
    </tr>
  <% end %>
  </table>
<% else %>
  <p>No students are enrolled.</p>
<% end %>

<p><%= link_to "Back", @course %></p>

students/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Roll', roll_course_path(@course) %> |
<%= link_to 'Back', courses_path %>