students/config/routes.rb
Students::Application.routes.draw do
  resources :courses do
    member do
      get :roll
    end
  end

  resources :students do
    resources :awards

    member do
      get :courses
      post :course_add
      post :course_remove
    end
  end

end

students/app/models/award.rb
class Award < ActiveRecord::Base
  attr_accessible :name, :student_id, :year
  belongs_to :student
  validates_presence_of :student
end

students/app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # GET /awards
  # GET /awards.json
  before_filter :get_student

  def index
    @awards = @student.awards

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @awards }
    end
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
    @award = @student.awards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/new
  # GET /awards/new.json
  def new
    @award = @student.awards.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @award }
    end
  end

  # GET /awards/1/edit
  def edit
    @award = @student.awards.find(params[:id])
  end

  # POST /awards
  # POST /awards.json
  def create
    @award = @student.awards.build(params[:award])

    respond_to do |format|
      if @award.save
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully created.' }
        format.json { render json: @award, status: :created, location: @award }
      else
        format.html { render action: "new" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /awards/1
  # PUT /awards/1.json
  def update
    @award = @student.awards.find(params[:id])

    respond_to do |format|
      if @award.update_attributes(params[:award])
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award = @student.awards..find(params[:id])
    @award.destroy

    respond_to do |format|
      format.html { redirect_to (student_awards_path(@student)) }
      format.json { head :no_content }
    end
  end

  private
  # get_student converts the student_id given by the routing into an @student
  # object, for use here and in the view.
  def get_student
    @student = Student.find(params[:student_id])
  end
end

students/app/helpers/awards_helper.rb
module AwardsHelper
end

students/app/views/awards/_form.html.erb
<%= form_for([@student, @award]) do |f| %>
  <% if @award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% @award.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

students/app/views/awards/edit.html.erb
<h1>Editing award for <%= @student.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', [@student, @award] %> |
<%= link_to 'Back', student_awards_path(@student) %>

students/app/views/awards/index.html.erb
<h1>Awards for <%= @student.name %></h1>

<% if !@student.awards.empty? %>
<table>
  <tr>
    <th>Year</th>
    <th>Student</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% for award in @awards %>
  <tr>
    <td><%= award.name %></td>
    <td><%= award.year %></td>
    <td><%= award.student.name %></td>
    <td><%= link_to 'Show', [@student, award] %></td>
    <td><%= link_to 'Edit', edit_student_award_path(@student, award) %></td>
    <td><%= link_to 'Destroy', [@student, award], :method => :delete, :confirm => 'Are you sure?' %></td>
  </tr>
<% end %>
</table>

<br />

<% else %>
  <p><%= @student.given_name %> hasn't won any awards yet.</p>
<% end %>

<p>
  <%= link_to 'New Award', new_student_award_path(@student) %> |
  <%= link_to 'Back', @student %>
</p>

students/app/views/awards/new.html.erb
<h1>New award for <%= @student.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', awards_path %>

students/app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @award.name %>
</p>

<p>
  <b>Year:</b>
  <%= @award.year %>
</p>

<p>
  <b>Student:</b>
  <%= @award.student.name %>
</p>


<%= link_to 'Edit', edit_student_award_path(@student, @award) %> |
<%= link_to 'Back', student_awards_path(@student) %>